package com.arshad.studdy_app_android_only.data.model;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/**
 * Maps to a row in {@code public.exam_sessions}.
 *
 * IMPORTANT: {@code id} is a {@code bigint GENERATED BY DEFAULT AS IDENTITY}
 * on the live database — use {@code long}, NOT String/UUID.
 */
public class ExamSession {

    @SerializedName("id")
    public Long id;                      // bigint — NOT uuid

    @SerializedName("exam_code")
    public String examCode;

    @SerializedName("enrollment_number")
    public String enrollmentNumber;

    @SerializedName("student_name")
    public String studentName;

    @SerializedName("joined_at")
    public String joinedAt;

    @SerializedName("submitted_at")
    public String submittedAt;

    /** "active" or "submitted" */
    @SerializedName("status")
    public String status;

    @SerializedName("created_at")
    public String createdAt;

    @SerializedName("warnings")
    public int warnings;

    @SerializedName("warnings_log")
    public List<WarningEvent> warningsLog;

    @SerializedName("last_warning_at")
    public String lastWarningAt;

    @SerializedName("last_warning_type")
    public String lastWarningType;

    @SerializedName("last_heartbeat")
    public String lastHeartbeat;

    @SerializedName("current_answers")
    public List<Integer> currentAnswers;

    @SerializedName("last_question_index")
    public int lastQuestionIndex;

    // ── Warning event (element of warnings_log JSONB array) ───────────────

    public static class WarningEvent {
        @SerializedName("type")
        public String type;

        @SerializedName("timestamp")
        public String timestamp;

        public WarningEvent(String type, String timestamp) {
            this.type = type;
            this.timestamp = timestamp;
        }
    }

    // ── Warning type constants ─────────────────────────────────────────────
    public static final String WARN_FACE_NOT_DETECTED = "face_not_detected";
    public static final String WARN_MULTIPLE_FACES    = "multiple_faces";
    public static final String WARN_LOOKING_AWAY      = "looking_away";
    public static final String WARN_APP_SWITCH        = "app_switch";
}
